// Package extract provides candidate extraction primitives shared by feature packages.
package extract

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

const (
	StatusDetected  = "detected"
	StatusDraft     = "draft"
	StatusInReview  = "in_review"
	StatusApproved  = "approved"
	StatusPublished = "published"
	StatusRejected  = "rejected"
	StatusDeferred  = "deferred"
	StatusFailed    = "failed"
	StatusDisabled  = "disabled"
	StatusDeleted   = "deleted"
)

const (
	ActionCreate     = "create"
	ActionTransition = "transition"
	ActionDelete     = "delete"
	ActionRestore    = "restore"
)

var (
	ErrNotFound           = errors.New("candidate not found")
	ErrInvalidStatus      = errors.New("invalid candidate status")
	ErrInvalidTransition  = errors.New("invalid candidate status transition")
	ErrCandidateDeleted   = errors.New("candidate is deleted")
	ErrCandidateNotDelete = errors.New("candidate is not deleted")
)

// DefaultDBPath is the database used by the index command unless --db is set.
// Candidate storage deliberately opens this path independently from internal/index.
var DefaultDBPath = filepath.Join(userHome(), ".cache", "session-finder", "index.db")

var validStatuses = map[string]struct{}{
	StatusDetected: {}, StatusDraft: {}, StatusInReview: {}, StatusApproved: {},
	StatusPublished: {}, StatusRejected: {}, StatusDeferred: {}, StatusFailed: {},
	StatusDisabled: {}, StatusDeleted: {},
}

// transitions lists deliberate state-machine edges. Deleted candidates are
// restored through Restore, so they have no ordinary outgoing edge.
var transitions = map[string]map[string]struct{}{
	StatusDetected: {
		StatusDraft: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusDraft: {
		StatusInReview: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusInReview: {
		StatusApproved: {}, StatusRejected: {}, StatusDeferred: {}, StatusFailed: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusApproved: {
		StatusPublished: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusPublished: {
		StatusDisabled: {}, StatusDeleted: {},
	},
	StatusRejected: {
		StatusDraft: {}, StatusDeferred: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusDeferred: {
		StatusDraft: {}, StatusInReview: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusFailed: {
		StatusDraft: {}, StatusInReview: {}, StatusDeferred: {}, StatusDisabled: {}, StatusDeleted: {},
	},
	StatusDisabled: {
		StatusDraft: {}, StatusDeleted: {},
	},
	StatusDeleted: {},
}

// CanTransition reports whether a status change is accepted by the state machine.
func CanTransition(from, to string) bool {
	if !ValidStatus(from) || !ValidStatus(to) || from == StatusDeleted {
		return false
	}
	_, ok := transitions[from][to]
	return ok
}

// ValidStatus reports whether status is one of the persisted candidate states.
func ValidStatus(status string) bool {
	_, ok := validStatuses[status]
	return ok
}

// ValidateTransition returns a descriptive error for an invalid state change.
func ValidateTransition(from, to string) error {
	if !ValidStatus(from) || !ValidStatus(to) {
		return fmt.Errorf("%w: %q -> %q", ErrInvalidStatus, from, to)
	}
	if !CanTransition(from, to) {
		return fmt.Errorf("%w: %q -> %q", ErrInvalidTransition, from, to)
	}
	return nil
}

// Candidate is the durable representation of an extracted candidate.
type Candidate struct {
	ID                string          `json:"id"`
	SessionID         string          `json:"session_id"`
	Tool              string          `json:"tool"`
	SourcePath        string          `json:"source_path"`
	Kind              string          `json:"kind"`
	Title             string          `json:"title"`
	Summary           string          `json:"summary"`
	Payload           json.RawMessage `json:"payload"`
	Status            string          `json:"status"`
	CreatedAt         string          `json:"created_at"`
	UpdatedAt         string          `json:"updated_at"`
	DeletedAt         string          `json:"deleted_at,omitempty"`
	Confidence        float64         `json:"confidence,omitempty"`
	SuccessEvidence   []string        `json:"success_evidence,omitempty"`
	OneOffRisk        float64         `json:"one_off_risk,omitempty"`
	SecretRisk        float64         `json:"secret_risk,omitempty"`
	RecommendedAction string          `json:"recommended_action,omitempty"`
	Version           int64           `json:"version"`
}

// CandidateInput contains fields used when creating a candidate. Status
// defaults to detected; ID and timestamps are generated by the store.
type CandidateInput struct {
	ID                string
	SessionID         string
	Tool              string
	SourcePath        string
	Kind              string
	Title             string
	Summary           string
	Payload           json.RawMessage
	Status            string
	Actor             string
	Reason            string
	Confidence        float64
	SuccessEvidence   []string
	OneOffRisk        float64
	SecretRisk        float64
	RecommendedAction string
}

// CreateInput is retained as a readable alias for callers that prefer the
// operation-oriented name.
type CreateInput = CandidateInput

// CandidateEvent is an append-only audit record.
type CandidateEvent struct {
	ID          int64  `json:"id"`
	CandidateID string `json:"candidate_id"`
	SessionID   string `json:"session_id"`
	Action      string `json:"action"`
	Actor       string `json:"actor"`
	Reason      string `json:"reason"`
	Timestamp   string `json:"timestamp"`
	BeforeHash  string `json:"before_hash"`
	AfterHash   string `json:"after_hash"`
}

// ListOptions filters candidate queries. Deleted candidates are excluded by
// default unless IncludeDeleted is true or Status is explicitly deleted.
type ListOptions struct {
	Status         string
	SessionID      string
	Kind           string
	IncludeDeleted bool
	Limit          int
}

// Store owns one independently opened SQLite connection. It never relies on
// internal/index's connection or unexported helpers, allowing both packages to
// evolve independently while sharing the same database file.
type Store struct {
	db     *sql.DB
	path   string
	now    func() time.Time
	ownsDB bool
}

// CandidateStore is a compatibility alias emphasizing the store's purpose.
type CandidateStore = Store

func userHome() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return ""
	}
	return home
}

func sqliteURI(path string) string {
	if path == ":memory:" || strings.HasPrefix(path, "file:") {
		return path
	}
	escaped := url.PathEscape(path)
	escaped = strings.ReplaceAll(escaped, "%2F", "/")
	escaped = strings.ReplaceAll(escaped, "%2f", "/")
	return "file:" + escaped
}

// Open opens path and creates candidate tables if necessary. An empty path uses
// DefaultDBPath. The connection is intentionally created here rather than by
// importing internal/index.Open.
func Open(path string) (*Store, error) {
	if path == "" {
		path = DefaultDBPath
	}
	if path != ":memory:" && !strings.HasPrefix(path, "file:") {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return nil, err
		}
	}
	db, err := sql.Open("sqlite", sqliteURI(path))
	if err != nil {
		return nil, err
	}
	db.SetMaxOpenConns(1)
	for _, pragma := range []string{
		"PRAGMA foreign_keys = ON",
		"PRAGMA busy_timeout = 5000",
		"PRAGMA journal_mode = WAL",
	} {
		if _, err := db.Exec(pragma); err != nil {
			db.Close()
			return nil, err
		}
	}
	store := &Store{db: db, path: path, now: time.Now, ownsDB: true}
	if err := store.InitializeSchema(context.Background()); err != nil {
		db.Close()
		return nil, err
	}
	return store, nil
}

// OpenStore is an explicit synonym for Open.
func OpenStore(path string) (*Store, error) { return Open(path) }

// OpenCandidateStore is an explicit operation-oriented synonym for Open.
func OpenCandidateStore(path string) (*Store, error) { return Open(path) }

// NewStore opens a candidate store. It mirrors Open for callers that use
// constructor naming.
func NewStore(path string) (*Store, error) { return Open(path) }

// NewCandidateStore opens a candidate store. It mirrors Open for downstream
// feature packages that use the domain-oriented constructor name.
func NewCandidateStore(path string) (*Store, error) { return Open(path) }

// OpenDB wraps an already-opened database while preserving the caller's
// connection ownership. Prefer Open for the normal self-owned path-based store.
func OpenDB(db *sql.DB, path string) (*Store, error) {
	if db == nil {
		return nil, errors.New("nil database")
	}
	db.SetMaxOpenConns(1)
	store := &Store{db: db, path: path, now: time.Now}
	if err := store.InitializeSchema(context.Background()); err != nil {
		return nil, err
	}
	return store, nil
}

// Path returns the path supplied to Open.
func (s *Store) Path() string { return s.path }

// Close closes the independently owned database connection. A store created by
// OpenDB leaves the caller-owned connection open.
func (s *Store) Close() error {
	if s == nil || s.db == nil || !s.ownsDB {
		return nil
	}
	return s.db.Close()
}

// InitializeSchema is idempotent and safe to call after internal/index has
// created its own tables.
func (s *Store) InitializeSchema(ctx context.Context) error {
	if s == nil || s.db == nil {
		return errors.New("nil candidate store")
	}
	return InitializeSchema(ctx, s.db)
}

// InitializeSchema creates candidate tables on an independently opened SQLite
// connection. It is useful when a caller owns the connection lifecycle.
func InitializeSchema(ctx context.Context, db *sql.DB) error {
	if db == nil {
		return errors.New("nil database")
	}
	const schema = `
CREATE TABLE IF NOT EXISTS candidates (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL DEFAULT '',
    tool TEXT NOT NULL DEFAULT '',
    source_path TEXT NOT NULL DEFAULT '',
    kind TEXT NOT NULL DEFAULT '',
    title TEXT NOT NULL DEFAULT '',
    summary TEXT NOT NULL DEFAULT '',
    payload TEXT NOT NULL DEFAULT '{}',
    status TEXT NOT NULL DEFAULT 'detected' CHECK (status IN ('detected','draft','in_review','approved','published','rejected','deferred','failed','disabled','deleted')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT NOT NULL DEFAULT '',
    confidence REAL NOT NULL DEFAULT 0,
    success_evidence TEXT NOT NULL DEFAULT '[]',
    one_off_risk REAL NOT NULL DEFAULT 0,
    secret_risk REAL NOT NULL DEFAULT 0,
    recommended_action TEXT NOT NULL DEFAULT '',
    version INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS candidates_status ON candidates(status, updated_at);
CREATE INDEX IF NOT EXISTS candidates_session ON candidates(session_id, updated_at);
CREATE INDEX IF NOT EXISTS candidates_kind ON candidates(kind, updated_at);
CREATE TABLE IF NOT EXISTS candidate_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    candidate_id TEXT NOT NULL REFERENCES candidates(id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL DEFAULT '',
    action TEXT NOT NULL,
    actor TEXT NOT NULL DEFAULT '',
    reason TEXT NOT NULL DEFAULT '',
    timestamp TEXT NOT NULL,
    before_hash TEXT NOT NULL DEFAULT '',
    after_hash TEXT NOT NULL CHECK (after_hash <> '')
);
CREATE INDEX IF NOT EXISTS candidate_events_candidate ON candidate_events(candidate_id, id);
CREATE INDEX IF NOT EXISTS candidate_events_session ON candidate_events(session_id, id);
CREATE TRIGGER IF NOT EXISTS candidate_events_no_update
BEFORE UPDATE ON candidate_events BEGIN
    SELECT RAISE(ABORT, 'candidate_events is append-only');
END;
CREATE TRIGGER IF NOT EXISTS candidate_events_no_delete
BEFORE DELETE ON candidate_events BEGIN
    SELECT RAISE(ABORT, 'candidate_events is append-only');
END;
CREATE TABLE IF NOT EXISTS candidate_trash (
    candidate_id TEXT PRIMARY KEY REFERENCES candidates(id) ON DELETE RESTRICT,
    session_id TEXT NOT NULL DEFAULT '',
    deleted_at TEXT NOT NULL,
    previous_status TEXT NOT NULL,
    snapshot TEXT NOT NULL
);
`
	_, err := db.ExecContext(ctx, schema)
	return err
}

func newID() (string, error) {
	var bytes [16]byte
	if _, err := rand.Read(bytes[:]); err != nil {
		return "", err
	}
	return "candidate-" + hex.EncodeToString(bytes[:]), nil
}

func timestamp(now time.Time) string { return now.UTC().Format(time.RFC3339Nano) }

func normalizedPayload(payload json.RawMessage) (json.RawMessage, error) {
	if len(payload) == 0 {
		return json.RawMessage(`{}`), nil
	}
	if !json.Valid(payload) {
		return nil, errors.New("candidate payload must be valid JSON")
	}
	var value any
	if err := json.Unmarshal(payload, &value); err != nil {
		return nil, err
	}
	canonical, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	return json.RawMessage(canonical), nil
}

func normalizeEvidence(values []string) []string {
	if len(values) == 0 {
		return []string{}
	}
	result := append([]string(nil), values...)
	return result
}

func evidenceJSON(values []string) (string, error) {
	data, err := json.Marshal(normalizeEvidence(values))
	return string(data), err
}

func decodeEvidence(value string) []string {
	if value == "" {
		return []string{}
	}
	var result []string
	if err := json.Unmarshal([]byte(value), &result); err != nil || result == nil {
		return []string{}
	}
	return result
}

func clampRisk(value float64) float64 {
	if value < 0 {
		return 0
	}
	if value > 1 {
		return 1
	}
	return value
}

func candidateHash(candidate Candidate) string {
	state := struct {
		ID                string          `json:"id"`
		SessionID         string          `json:"session_id"`
		Tool              string          `json:"tool"`
		SourcePath        string          `json:"source_path"`
		Kind              string          `json:"kind"`
		Title             string          `json:"title"`
		Summary           string          `json:"summary"`
		Payload           json.RawMessage `json:"payload"`
		Status            string          `json:"status"`
		CreatedAt         string          `json:"created_at"`
		UpdatedAt         string          `json:"updated_at"`
		DeletedAt         string          `json:"deleted_at"`
		Confidence        float64         `json:"confidence"`
		SuccessEvidence   []string        `json:"success_evidence"`
		OneOffRisk        float64         `json:"one_off_risk"`
		SecretRisk        float64         `json:"secret_risk"`
		RecommendedAction string          `json:"recommended_action"`
		Version           int64           `json:"version"`
	}{
		ID: candidate.ID, SessionID: candidate.SessionID, Tool: candidate.Tool,
		SourcePath: candidate.SourcePath, Kind: candidate.Kind, Title: candidate.Title,
		Summary: candidate.Summary, Payload: candidate.Payload, Status: candidate.Status,
		CreatedAt: candidate.CreatedAt, UpdatedAt: candidate.UpdatedAt,
		DeletedAt: candidate.DeletedAt, Confidence: candidate.Confidence,
		SuccessEvidence: normalizeEvidence(candidate.SuccessEvidence), OneOffRisk: candidate.OneOffRisk,
		SecretRisk: candidate.SecretRisk, RecommendedAction: candidate.RecommendedAction,
		Version: candidate.Version,
	}
	data, _ := json.Marshal(state)
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// Hash returns the stable SHA-256 hash used by audit events.
func Hash(candidate Candidate) string { return candidateHash(candidate) }

func candidateFromInput(input CandidateInput, now string) (Candidate, error) {
	id := strings.TrimSpace(input.ID)
	if id == "" {
		var err error
		id, err = newID()
		if err != nil {
			return Candidate{}, err
		}
	}
	status := strings.TrimSpace(input.Status)
	if status == "" {
		status = StatusDetected
	}
	if !ValidStatus(status) || status == StatusDeleted {
		return Candidate{}, fmt.Errorf("%w: %q", ErrInvalidStatus, status)
	}
	payload, err := normalizedPayload(input.Payload)
	if err != nil {
		return Candidate{}, err
	}
	evidence := normalizeEvidence(input.SuccessEvidence)
	return Candidate{
		ID: id, SessionID: input.SessionID, Tool: input.Tool, SourcePath: input.SourcePath,
		Kind: input.Kind, Title: input.Title, Summary: input.Summary, Payload: payload,
		Status: status, CreatedAt: now, UpdatedAt: now, Confidence: clampRisk(input.Confidence),
		SuccessEvidence: evidence, OneOffRisk: clampRisk(input.OneOffRisk), SecretRisk: clampRisk(input.SecretRisk),
		RecommendedAction: input.RecommendedAction, Version: 1,
	}, nil
}

func scanCandidate(scanner interface{ Scan(...any) error }) (Candidate, error) {
	var candidate Candidate
	var payload, evidence string
	if err := scanner.Scan(&candidate.ID, &candidate.SessionID, &candidate.Tool, &candidate.SourcePath,
		&candidate.Kind, &candidate.Title, &candidate.Summary, &payload, &candidate.Status,
		&candidate.CreatedAt, &candidate.UpdatedAt, &candidate.DeletedAt, &candidate.Confidence,
		&evidence, &candidate.OneOffRisk, &candidate.SecretRisk, &candidate.RecommendedAction, &candidate.Version); err != nil {
		return Candidate{}, err
	}
	candidate.Payload = json.RawMessage(payload)
	candidate.SuccessEvidence = decodeEvidence(evidence)
	return candidate, nil
}

const candidateColumns = `id, session_id, tool, source_path, kind, title, summary, payload,
 status, created_at, updated_at, deleted_at, confidence, success_evidence, one_off_risk,
 secret_risk, recommended_action, version`

// Get returns one candidate by ID.
func (s *Store) Get(ctx context.Context, id string) (Candidate, error) {
	row := s.db.QueryRowContext(ctx, "SELECT "+candidateColumns+" FROM candidates WHERE id = ?", id)
	candidate, err := scanCandidate(row)
	if errors.Is(err, sql.ErrNoRows) {
		return Candidate{}, fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	return candidate, err
}

// GetCandidate is an explicit synonym for Get.
func (s *Store) GetCandidate(ctx context.Context, id string) (Candidate, error) {
	return s.Get(ctx, id)
}

// Create inserts a candidate and its create audit event in one transaction.
func (s *Store) Create(ctx context.Context, input CandidateInput) (Candidate, error) {
	now := timestamp(s.now())
	candidate, err := candidateFromInput(input, now)
	if err != nil {
		return Candidate{}, err
	}
	evidence, err := evidenceJSON(candidate.SuccessEvidence)
	if err != nil {
		return Candidate{}, err
	}
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Candidate{}, err
	}
	rollback := func(err error) (Candidate, error) {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	_, err = tx.ExecContext(ctx, `INSERT INTO candidates(`+candidateColumns+`)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		candidate.ID, candidate.SessionID, candidate.Tool, candidate.SourcePath, candidate.Kind,
		candidate.Title, candidate.Summary, string(candidate.Payload), candidate.Status,
		candidate.CreatedAt, candidate.UpdatedAt, candidate.DeletedAt, candidate.Confidence,
		evidence, candidate.OneOffRisk, candidate.SecretRisk, candidate.RecommendedAction, candidate.Version)
	if err != nil {
		return rollback(err)
	}
	if err := insertEventAt(ctx, tx, candidate, ActionCreate, input.Actor, input.Reason, "", candidateHash(candidate), now); err != nil {
		return rollback(err)
	}
	if err := tx.Commit(); err != nil {
		return Candidate{}, err
	}
	return candidate, nil
}

// CreateCandidate is an explicit synonym for Create.
func (s *Store) CreateCandidate(ctx context.Context, input CandidateInput) (Candidate, error) {
	return s.Create(ctx, input)
}

func insertEventAt(ctx context.Context, tx *sql.Tx, candidate Candidate, action, actor, reason, beforeHash, afterHash, at string) error {
	_, err := tx.ExecContext(ctx, `INSERT INTO candidate_events
		(candidate_id, session_id, action, actor, reason, timestamp, before_hash, after_hash)
		VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, candidate.ID, candidate.SessionID, action, actor, reason,
		at, beforeHash, afterHash)
	return err
}

func (s *Store) transition(ctx context.Context, id, to, actor, reason, action string) (Candidate, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Candidate{}, err
	}
	var current Candidate
	row := tx.QueryRowContext(ctx, "SELECT "+candidateColumns+" FROM candidates WHERE id = ?", id)
	current, err = scanCandidate(row)
	if errors.Is(err, sql.ErrNoRows) {
		_ = tx.Rollback()
		return Candidate{}, fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if err := ValidateTransition(current.Status, to); err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	beforeHash := candidateHash(current)
	now := timestamp(s.now())
	updated := current
	updated.Status = to
	updated.UpdatedAt = now
	updated.Version++
	if to == StatusDeleted {
		updated.DeletedAt = now
	}
	evidence, err := evidenceJSON(updated.SuccessEvidence)
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if to == StatusDeleted {
		snapshot, marshalErr := json.Marshal(current)
		if marshalErr != nil {
			_ = tx.Rollback()
			return Candidate{}, marshalErr
		}
		if _, err := tx.ExecContext(ctx, `INSERT OR REPLACE INTO candidate_trash
			(candidate_id, session_id, deleted_at, previous_status, snapshot) VALUES (?, ?, ?, ?, ?)`,
			current.ID, current.SessionID, now, current.Status, string(snapshot)); err != nil {
			_ = tx.Rollback()
			return Candidate{}, err
		}
	}
	result, err := tx.ExecContext(ctx, `UPDATE candidates SET status = ?, updated_at = ?, deleted_at = ?,
		confidence = ?, success_evidence = ?, one_off_risk = ?, secret_risk = ?, recommended_action = ?, version = ?
		WHERE id = ? AND version = ?`, updated.Status, updated.UpdatedAt, updated.DeletedAt,
		updated.Confidence, evidence, updated.OneOffRisk, updated.SecretRisk, updated.RecommendedAction,
		updated.Version, updated.ID, current.Version)
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if affected, err := result.RowsAffected(); err != nil || affected != 1 {
		_ = tx.Rollback()
		if err != nil {
			return Candidate{}, err
		}
		return Candidate{}, errors.New("candidate changed concurrently")
	}
	at := now
	if action == "" {
		action = ActionTransition
	}
	if err := insertEventAt(ctx, tx, updated, action, actor, reason, beforeHash, candidateHash(updated), at); err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if err := tx.Commit(); err != nil {
		return Candidate{}, err
	}
	return updated, nil
}

// Transition changes a candidate's status and appends an audit event. The
// candidate row and event are committed atomically.
func (s *Store) Transition(ctx context.Context, id, to, actor, reason string) (Candidate, error) {
	if to == StatusDeleted {
		return s.transition(ctx, id, to, actor, reason, ActionDelete)
	}
	return s.transition(ctx, id, to, actor, reason, ActionTransition)
}

// TransitionStatus is an explicit synonym for Transition.
func (s *Store) TransitionStatus(ctx context.Context, id, to, actor, reason string) (Candidate, error) {
	return s.Transition(ctx, id, to, actor, reason)
}

// Delete moves a candidate into the recoverable trash table and marks it
// deleted. No candidate row is physically removed.
func (s *Store) Delete(ctx context.Context, id, actor, reason string) (Candidate, error) {
	return s.Transition(ctx, id, StatusDeleted, actor, reason)
}

// DeleteCandidate is an explicit synonym for Delete.
func (s *Store) DeleteCandidate(ctx context.Context, id, actor, reason string) (Candidate, error) {
	return s.Delete(ctx, id, actor, reason)
}

// Restore returns a deleted candidate to the status captured in trash.
func (s *Store) Restore(ctx context.Context, id, actor, reason string) (Candidate, error) {
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return Candidate{}, err
	}
	row := tx.QueryRowContext(ctx, "SELECT "+candidateColumns+" FROM candidates WHERE id = ?", id)
	current, err := scanCandidate(row)
	if errors.Is(err, sql.ErrNoRows) {
		_ = tx.Rollback()
		return Candidate{}, fmt.Errorf("%w: %s", ErrNotFound, id)
	}
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if current.Status != StatusDeleted {
		_ = tx.Rollback()
		return Candidate{}, fmt.Errorf("%w: %s", ErrCandidateNotDelete, id)
	}
	var previousStatus, snapshot string
	if err := tx.QueryRowContext(ctx, "SELECT previous_status, snapshot FROM candidate_trash WHERE candidate_id = ?", id).Scan(&previousStatus, &snapshot); errors.Is(err, sql.ErrNoRows) {
		_ = tx.Rollback()
		return Candidate{}, fmt.Errorf("%w: trash snapshot missing for %s", ErrCandidateNotDelete, id)
	} else if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if !ValidStatus(previousStatus) || previousStatus == StatusDeleted {
		_ = tx.Rollback()
		return Candidate{}, fmt.Errorf("%w: invalid trash status %q", ErrInvalidStatus, previousStatus)
	}
	var snapshotCandidate Candidate
	if err := json.Unmarshal([]byte(snapshot), &snapshotCandidate); err != nil || snapshotCandidate.ID != id {
		_ = tx.Rollback()
		if err == nil {
			err = errors.New("trash snapshot candidate ID mismatch")
		}
		return Candidate{}, fmt.Errorf("%w: %v", ErrCandidateNotDelete, err)
	}
	beforeHash := candidateHash(current)
	now := timestamp(s.now())
	updated := snapshotCandidate
	updated.Status = previousStatus
	updated.DeletedAt = ""
	updated.UpdatedAt = now
	updated.Version = current.Version + 1
	evidence, err := evidenceJSON(updated.SuccessEvidence)
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	result, err := tx.ExecContext(ctx, `UPDATE candidates SET status = ?, updated_at = ?, deleted_at = ?,
		confidence = ?, success_evidence = ?, one_off_risk = ?, secret_risk = ?, recommended_action = ?, version = ?
		WHERE id = ? AND version = ?`, updated.Status, updated.UpdatedAt, updated.DeletedAt,
		updated.Confidence, evidence, updated.OneOffRisk, updated.SecretRisk, updated.RecommendedAction,
		updated.Version, updated.ID, current.Version)
	if err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if affected, err := result.RowsAffected(); err != nil || affected != 1 {
		_ = tx.Rollback()
		if err != nil {
			return Candidate{}, err
		}
		return Candidate{}, errors.New("candidate changed concurrently")
	}
	if err := insertEventAt(ctx, tx, updated, ActionRestore, actor, reason, beforeHash, candidateHash(updated), now); err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if _, err := tx.ExecContext(ctx, "DELETE FROM candidate_trash WHERE candidate_id = ?", id); err != nil {
		_ = tx.Rollback()
		return Candidate{}, err
	}
	if err := tx.Commit(); err != nil {
		return Candidate{}, err
	}
	return updated, nil
}

// RestoreCandidate is an explicit synonym for Restore.
func (s *Store) RestoreCandidate(ctx context.Context, id, actor, reason string) (Candidate, error) {
	return s.Restore(ctx, id, actor, reason)
}

// List returns candidates in stable newest-first order.
func (s *Store) List(ctx context.Context, options ListOptions) ([]Candidate, error) {
	where := []string{}
	args := []any{}
	if options.Status != "" {
		if !ValidStatus(options.Status) {
			return nil, fmt.Errorf("%w: %q", ErrInvalidStatus, options.Status)
		}
		where = append(where, "status = ?")
		args = append(args, options.Status)
	} else if !options.IncludeDeleted {
		where = append(where, "status <> ?")
		args = append(args, StatusDeleted)
	}
	if options.SessionID != "" {
		where = append(where, "session_id = ?")
		args = append(args, options.SessionID)
	}
	if options.Kind != "" {
		where = append(where, "kind = ?")
		args = append(args, options.Kind)
	}
	query := "SELECT " + candidateColumns + " FROM candidates"
	if len(where) > 0 {
		query += " WHERE " + strings.Join(where, " AND ")
	}
	query += " ORDER BY updated_at DESC, id ASC"
	if options.Limit > 0 {
		query += " LIMIT ?"
		args = append(args, options.Limit)
	}
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := []Candidate{}
	for rows.Next() {
		candidate, err := scanCandidate(rows)
		if err != nil {
			return nil, err
		}
		result = append(result, candidate)
	}
	return result, rows.Err()
}

// ListCandidates is an explicit synonym for List.
func (s *Store) ListCandidates(ctx context.Context, options ListOptions) ([]Candidate, error) {
	return s.List(ctx, options)
}

// Events returns the complete append-only audit trail for a candidate.
func (s *Store) Events(ctx context.Context, candidateID string) ([]CandidateEvent, error) {
	rows, err := s.db.QueryContext(ctx, `SELECT id, candidate_id, session_id, action, actor,
		reason, timestamp, before_hash, after_hash FROM candidate_events WHERE candidate_id = ? ORDER BY id`, candidateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	result := []CandidateEvent{}
	for rows.Next() {
		var event CandidateEvent
		if err := rows.Scan(&event.ID, &event.CandidateID, &event.SessionID, &event.Action,
			&event.Actor, &event.Reason, &event.Timestamp, &event.BeforeHash, &event.AfterHash); err != nil {
			return nil, err
		}
		result = append(result, event)
	}
	return result, rows.Err()
}

// CandidateEvents is an explicit synonym for Events.
func (s *Store) CandidateEvents(ctx context.Context, candidateID string) ([]CandidateEvent, error) {
	return s.Events(ctx, candidateID)
}

// Trash returns deleted candidates currently present in recoverable trash.
func (s *Store) Trash(ctx context.Context, limit int) ([]Candidate, error) {
	return s.List(ctx, ListOptions{Status: StatusDeleted, IncludeDeleted: true, Limit: limit})
}

// SortStatuses returns all statuses in deterministic display order.
func SortStatuses() []string {
	result := make([]string, 0, len(validStatuses))
	for status := range validStatuses {
		result = append(result, status)
	}
	sort.Strings(result)
	return result
}

// SetNowForTesting replaces the clock used for newly written records. It is
// intended for deterministic package tests and should not be used by runtime
// callers.
func (s *Store) SetNowForTesting(now func() time.Time) {
	if now == nil {
		s.now = time.Now
		return
	}
	s.now = now
}

// CandidateHashForAudit exposes the event hash calculation without exposing
// storage internals.
func CandidateHashForAudit(candidate Candidate) string { return candidateHash(candidate) }

// IsNotFound reports whether an error represents a missing candidate.
func IsNotFound(err error) bool { return errors.Is(err, ErrNotFound) }

// IsInvalidTransition reports whether an error was raised by the state machine.
func IsInvalidTransition(err error) bool {
	return errors.Is(err, ErrInvalidTransition) || errors.Is(err, ErrInvalidStatus)
}
